= EKS Capsule Demo

This is a demo of Capsule multi-tenancy management on an AWS EKS cluster.

This demo is written making the following assumptions:

. You are running macOS or Linux
. You have an AWS account and permissions to fully manage:
.. CloudFormation stacksets
.. EKS clusters
.. IAM policies, roles, and users
. You have the following CLI tools installed and available in your $PATH
.. https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[AWS CLI] (With the default profile configured with credentials that have the listed permissions)
.. https://github.com/weaveworks/eksctl[eksctl]
.. https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git]
.. https://helm.sh/docs/intro/install/[helm]
.. https://kubernetes.io/docs/tasks/tools/[kubectl]

== Cluster Creation and Configuration

First clone this repo:

[source,shell]
----
 git clone https://github.com/cgahlon/eks-capsule-demo.git
----

Create a small test cluster using this command.
This step can take 20ish minutes on average but varies based on time of day/load in AWS.

[source,shell]
----
# from: https://capsule.clastix.io/docs/guides/managed-kubernetes/aws-eks/
eksctl create cluster --name=test-k8s --managed --node-type=t3.small --node-volume-size=20 --kubeconfig=kubeconfig.conf
----

Next we create a test IAM user named 'Alice'

[source,shell]
----
eval aws cloudformation deploy --capabilities CAPABILITY_NAMED_IAM   --parameter-overrides "ClusterName=test-k8s"   --stack-name "test-k8s-users" --template-file cloudformation/cluster-users.cf
----

Next create an identity mapping in the aws-auth configmap

[source,shell]
----
export AWS_CLOUDFORMATION_DETAILS=$(aws cloudformation describe-stacks --stack-name "test-k8s-users")
export ALICE_ROLE_ARN=$(echo "${AWS_CLOUDFORMATION_DETAILS}" | jq -r ".Stacks[0].Outputs[] | select(.OutputKey==\"RoleAliceArn\") .OutputValue")
export ALICE_USER_ACCESSKEY=$(echo "${AWS_CLOUDFORMATION_DETAILS}" | jq -r ".Stacks[0].Outputs[] | select(.OutputKey==\"AccessKeyAlice\") .OutputValue")
export ALICE_USER_SECRETACCESSKEY=$(echo "${AWS_CLOUDFORMATION_DETAILS}" | jq -r ".Stacks[0].Outputs[] | select(.OutputKey==\"SecretAccessKeyAlice\") .OutputValue")

eksctl create iamidentitymapping --cluster="test-k8s" --arn="${ALICE_ROLE_ARN}" --username alice --group capsule.clastix.io
----

Next we add the test users credentials and profile to the aws cli config files

[source,shell]
----
cat >> ~/.aws/config << EOF
[profile alice]
role_arn=${ALICE_ROLE_ARN}
source_profile=alice
EOF
----

[source,shell]
----
cat >> ~/.aws/credentials << EOF
[alice]
aws_access_key_id=${ALICE_USER_ACCESSKEY}
aws_secret_access_key=${ALICE_USER_SECRETACCESSKEY}
EOF
----

Deploy Capsule to the cluster using helm.

[source,shell]
----
helm repo add clastix https://clastix.github.io/charts
helm repo update
helm upgrade --install --namespace capsule-system --create-namespace capsule clastix/capsule --kubeconfig=kubeconfig.conf
----

Create a Capsule tenant.

[source,shell]
----
kubectl apply -f manifests/capsule/tenant.yaml --kubeconfig="kubeconfig.conf"
----

Clear any existing AWS related environment variables to avoid identity confusion since we are explicitly using ~/.aws/ contents for authentication of all users.

[source,shell]
----
unset AWS_PROFILE
unset AWS_SECRET_ACCESS_KEY
unset AWS_ACCESS_KEY_ID
----

== Test Capsule Permissions/Restrictions

Set the OS default kubeconfig for the test user

[source,shell]
----
AWS_PROFILE=alice kubectl auth can-i create ingresses --kubeconfig="kubeconfig.conf"
AWS_PROFILE=alice kubectl auth can-i create namespaces --kubeconfig="kubeconfig.conf"
----

Then we create a namespace as 'alice' and deploy our app to 'production'

[source,shell]
----
AWS_PROFILE=alice kubectl create ns oil-production --kubeconfig="kubeconfig.conf"
AWS_PROFILE=alice kubectl apply -n oil-production -f manifests/demo-apps/app-oil-production.yaml --kubeconfig="kubeconfig.conf"
----

Later that week Alice tries to create another ingres in the 'oil-development namespace' However, she copy/pasted the manifest from procution and forgot to update ingress host entry.
Capsule will block duplicate hostnames based on scope defined in the tenant config

[source,shell]
----
AWS_PROFILE=alice kubectl create namespace oil-development --kubeconfig="kubeconfig.conf"
AWS_PROFILE=alice kubectl -n oil-development apply -f manifests/demo-apps/app-oil-development.yaml --kubeconfig="kubeconfig.conf"
----

When you try to apply the `manifests/demo-apps/app-oil-development.yaml` file you end up getting denied with a message similar to this.

This proves the inability to create duplicate hosts on separate ingresses is properly denied.

`Error from server (Forbidden): error when creating "manifests/demo-apps/app-oil-development.yaml": admission webhook "ingress.capsule.clastix.io" denied the request: hostname web.oil.acmecorp.com is already used across the cluster: please, reach out to the system administrators`

Even cluster admins are not allowed to duplicate host names in tenant namespaces.
That is, those namespaces with a `capsule.clastix.io/tenant=<TENANT_NAME>` label.

[source,shell]
----
kubectl apply -f manifests/demo-apps/app-oil-admin.yaml -n oil-development --kubeconfig="kubeconfig.conf"
----

==== References

Many of the commands and code in this demo are derived from code in the Clastix/Capsule tutorial.

- https://capsule.clastix.io/docs/general/tutorial/[Capsule Tutorial]
- https://capsule.clastix.io/docs/guides/managed-kubernetes/aws-eks[Capsule on AWS EKS Guide]
- https://github.com/clastix/capsule[Capsule on GitHub]
